### ISSUE TITLE
Can't find Style Palette

### ISSUE THREAD

**Issue by danirui** [tikzit/tikzit#101]
I accidentally closed out of the window, and I can't find how to open it again. Sorry if this was a stupid question...I've been looking for a while now and still can't get it back :(

**Comment by 0xACE** [comment]
Wow, just noticed the small `x` to close the style palette. Cba to fix it atm, but The easiest approach would be removing your tikzit config:
`~/.config/tikzit/tikzit.conf`
or probablysomewhere under `%APPDATA%` on windows

**Comment by akissinger** [comment]
This is a tricky one to find. Right-click anywhere on toolbar and you'll see a checkbox to show style palette. I've intended for a long time to duplicate this functionality under View menu, but I haven't gotten to it.

**Comment by alangfor** [comment]
> I accidentally closed out of the window, and I can't find how to open it again. Sorry if this was a stupid question...I've been looking for a while now and still can't get it back :(

Yep... just had this same issue... Thanks for asking before!
