### ISSUE TITLE
Fine node position placement

### ISSUE THREAD

**Issue by btsp6** [tikzit/tikzit#110]
Apologies if this is somehow doable already, but I've been scouring the app and the readme and cannot locate how to position nodes off from the grid. 

It would be useful if something like ALT+dragging can place nodes at any arbitrary position. This is helpful for things with very precise but ad hoc spacing, like labels. This issue applies as well to the bezier curve control nodes.

**Comment by 0xACE** [comment]
`Ctrl-J` to bring up the bottom code editor and `Ctrl-T` to update according to the new code

https://user-images.githubusercontent.com/1482942/112825950-e0185400-907b-11eb-9240-4cdc5b2a6f3c.mp4

Same can be done for lines etc.

Regarding Alt-dragging, maybe it could be added in the future...

**Comment by akissinger** [comment]
By default, tikz coordinates are locked to increments of 0.25, but you can "nudge" nodes by increments of 0.05 using CTRL + SHIFT + arrow keys.

**Comment by bobthesmartypants** [comment]
Thank you very much, this is exactly what I needed! Alt-dragging would still be nice but I'm glad there is some way to do this.
