### ISSUE TITLE
Custom TikZit Shapes

### ISSUE THREAD

**Issue by pranshumalik14** [tikzit/tikzit#111]
Is there a possibility to have the same/similar shapes as in TikZ to show up on the drawing board on TikZit too? For example, if I am creating a circuit, I would like those components to show up as is on the drawing board as well.

Any input on this will be helpful, thanks!

**Comment by 0xACE** [comment]
No, not without modyfying the source code. Besides. you wouldn't be able to attach nodes into the "connect" pointes of the components, I added some shapes to my build but I wouldn't advice you approach this method. I'd advise you use tools specifically made for circuit drawings that can export to tikz...


https://user-images.githubusercontent.com/1482942/113485412-dd16cc80-949c-11eb-8e51-8bdb9e2fba6a.mp4

However, if you insist on creating it with `tikzit` i would recommend you create a couple of shapes like so:
```
\begin{tikzpicture}
	\begin{pgfonlayer}{nodelayer}
		\node [style=none] (0) at (-1, 1) {};
		\node [style=none] (1) at (1.25, 0) {};
		\node [style=none] (2) at (-1, -1) {};
		\node [style=none] (3) at (-0.5, -0.5) {};
		\node [style=none] (4) at (-0.5, 0.5) {};
		\node [style=L-textX] (5) at (-2.5, 0.5) {A};
		\node [style=L-textX] (6) at (-2.5, -0.5) {B};
		\node [style=L-textX] (7) at (3.25, 0) {Q};
	\end{pgfonlayer}
	\begin{pgfonlayer}{edgelayer}
		\draw [bend left] (0.center) to node [auto] {} (1.center);
		\draw [bend left] (1.center) to node [auto] {} (2.center);
		\draw [bend right] (2.center) to node [auto] {} (3.center);
		\draw (3.center) to node [auto] {} (4.center);
		\draw [bend right, looseness=0.75] (4.center) to node [auto] {} (0.center);
		\draw (4.center) to node [auto] {} (5);
		\draw (6) to node [auto] {} (3.center);
		\draw (1.center) to node [auto] {} (7);
	\end{pgfonlayer}
\end{tikzpicture}
```

(which is going to be a poor experience, infact I wouldn't be surprised if `tikz` already has a  circuit package...)

**Comment by pranshumalik14** [comment]
Yup, `tikz` has a circuit package but it is cumbersome to use and I was looking for a gui. But thanks!

**Comment by 0xACE** [comment]
![cap](https://user-images.githubusercontent.com/1482942/113494446-b75ae900-94d7-11eb-8d29-f185ffc0b5c9.png)
oh i forgot the picture of what the tikz above represented...

it's not pretty but meh... it works... I would still like to reiterate: they are most likely tools that can extract SVG's of circuits...

the `L-textX` node i used can be replaced by w/e, but i use it so that "empty" nodes allow text without having the line draw into the character...
