### ISSUE TITLE
macOS Big Sur - “TikZiT” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by nikchha** [tikzit/tikzit#113]
Opening tikzit in macOS Big Sur fails because the `dmg` is not signed according to the Apple guidelines.

I used `brew install --cask tikzit` to install tikzit.

**Comment by akissinger** [comment]
On previous versions of macOS, you could get around this by right clicking the app and clicking "Open" the first time you run it. Does this no longer work on big sur?

**Comment by nikchha** [comment]
Thank you very much for answering so quickly.

Unfortunately, clicking "Open" is not longer possible on macOS Big Sur.

![image](https://user-images.githubusercontent.com/37020365/113742076-88748b00-9702-11eb-8c21-25a1345683e5.png)

It would be great if you could verify the macOS distribution.

**Comment by akissinger** [comment]
If there is a way to sign the distro without having a paid developer account with Apple, I'm happy to look in to it.

**Comment by marc-git** [comment]
just right-click and select open. Then you can override it.

**Comment by Qottmann** [comment]
Having the same issue again on macOS 15.7.1. Right-click does not work. However, you can go settings > privacy & security > open app anyway there. Hope that helps anyone running into the same issue 👍
