### ISSUE TITLE
Bold font to edge - Increasing the thickness of edges 

### ISSUE THREAD

**Issue by AravindaSakshi** [tikzit/tikzit#117]
Dear All, 

How to include a edge with increased thickness ?? 

Thanking you

**Comment by akissinger** [comment]
Add a new edge style (see "Adding Styles" on https://tikzit.github.io/). Then add a new property "line width" to the edge style and set the width (e.g. "1pt"). You can also add atoms e.g. "thick", "very thick", "ultra thick". These all come from the PGF/tikz manual: https://www.bu.edu/math/files/2013/08/tikzpgfmanual.pdf

**Comment by AravindaSakshi** [comment]
Thanks you very much Aleks ---
