### ISSUE TITLE
How to use \boldsymbol{} in the labels?

### ISSUE THREAD

**Issue by andreasottosanti** [tikzit/tikzit#119]
I tried to write a formula like $\boldsymbol{\theta}$, but it failed in compiling.

Can someone suggest to me the correct way to use this style?

**Comment by akissinger** [comment]
You may just need to include amsmath in your tikzdefs file. I typically use the `bm` package for this and it works fine.

If you don't know what a tikzdefs file is, see: https://tikzit.github.io/#custom
