### ISSUE TITLE
Symmetry Mode

### ISSUE THREAD

**Issue by cuppajoeman** [tikzit/tikzit#123]
I went through the tutorial and it showed me that I could copy, reflect then merge, but that could be quite cumbersome if you want to to have symmetry in more ways than just a simple reflection.

For example here is some motivation from gimp: https://docs.gimp.org/2.10/en/gimp-symmetry-dialog.html

**Comment by 0xACE** [comment]
Not sure I'll be implementing this anytime soon.

Though I've had some success in integrating usage of `tikzit` along with `inkscape`, so maybe more complex things could be done in `inkscape` and combined with `tikzit` if you are inclined on using advanced symmetry for your tikzit drawings. (Iirc, it's basically importing the PDF into inkscape).
