### ISSUE TITLE
A "Double Scale" Option

### ISSUE THREAD

**Issue by danielrmagician** [tikzit/tikzit#125]
I wonder if it is possible to implement a "double scale" option, where all the coordinates of current points are multiplied by two so that finer detail can be added. For instance in my current image I would like to place a node at an x-coordinate halfway between two other nodes, but due to the grid being not detailed enough I can not do so.

**Comment by 0xACE** [comment]
I guess that could be easily done, as I haven't tinkered with the source in a while I don't feel comfortable trying this out atm.

For the moment the best way to get it done would be `CTRL-J` and modify the nodes that needs to be changed...

**Comment by akissinger** [comment]
Actually what tends to be much more convenient is the "nudge" feature (see https://tikzit.github.io/#editing). Select the node and hit `CTRL-SHIFT-arrow` to nudge the node by 1/10-th of a grid unit. So, to get halfway between 2 gridlines, hold `CTRL-SHIFT` and hit e.g. right arrow 5 times.

If you really want "double scale" everywhere, you can manually set a global scale of 0.5 in your tex code. For example, you could add this to your `.tikzdefs` file: `\tikzstyle{every picture}=[scale=0.5]`. I use to do this, but I found it to be annoying if I wanted to re-use pictures between papers with and without this scaling, so I stopped.
