### ISSUE TITLE
Fails to start with newer freetype version

### ISSUE THREAD

**Issue by fkohrt** [tikzit/tikzit#136]
When running on Fedora 36 with `freetype-2.12.1-1.fc36.x86_64` installed, I get the following error message:

```
~/Downloads/tikzit-linux/tikzit/opt/tikzit: symbol lookup error: /lib64/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
```

Only after a downgrade to `2.10.4` (available from [koji](https://koji.fedoraproject.org/koji/buildinfo?buildID=1786684)) it works:

```sh
sudo dnf downgrade ./freetype-2.10.4-4.fc35.x86_64.rpm ./freetype-devel-2.10.4-4.fc35.x86_64.rpm
```

See also ValveSoftware/steam-for-linux#7935

**Comment by akissinger** [comment]
This is probably due to the fact that there hasn't been a binary release in a LONG time. There will be a new release shortly, which should fix the issue.
