### ISSUE TITLE
Can it support xelatex or other mode that can solve Chinese?

### ISSUE THREAD

**Issue by zongpingding** [tikzit/tikzit#139]
I read the doc that tikzit only support pdflatex and setting its path by "Tools > Preferences tikzit > Preferences",i wander something about xelatex?
Then
I use the .tikzdefs file to include package ctex. but it turns out that "CTeX fontset `fandol' is unavailable in current (ctex) mode."
when i use the package xeCJK it return " Critical Package xeCJK Error: The xeCJK package requires XeTeX to function.".

i want to change pdflatex to xelatex? what  should i do?

**Comment by akissinger** [comment]
If you go to `Tools > Preferences` and set the "pdflatex location" to xelatex, it should run xelatex instead. It just expects any pdflatex-compatible binary here.
