### ISSUE TITLE
Tikzit crashes when I press the 'B' key. 

### ISSUE THREAD

**Issue by AJnsm** [tikzit/tikzit#140]
I'm on a MacBook Pro (2018), running macOS Monterey (12.6). When I open Tikzit, the keys S, N and E correctly switch between the tools, but pressing B crashes an quits the the programme instantly and triggers the "tikzit quit unexpectedly." popup. This only happens for the B key, not for any other letter, number, or character.

**Comment by gspr** [comment]
PR #141 fixes this for me. It seems that the b hotkey is tied to functionality no longer available in the program?
