### ISSUE TITLE
Error: Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created

### ISSUE THREAD

**Issue by bgavran** [tikzit/tikzit#142]
### Description
I am experiencing an error when trying to run TikZiT on Arch Linux. The error message is:
"Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created."

I have installed TikZiT using AUR and have Qt installed.

### Steps to Reproduce
1. Install TikZiT using AUR on Arch Linux.
2. Run `tikzit` in the terminal.

### Expected Behavior
TikZiT should start without any issues.

### Actual Behavior
The application starts with a blank window, and the error "Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created." is displayed in the console.

### System Information
- Operating System: Arch Linux (Kernel version: 6.2.12)
- TikZiT Version: 2.1.6-1
- Qt Version: 5.15.9

### What I Have Tried
1. Reinstalling TikZiT and its dependencies.
2. Running TikZiT with the following environment variables:
    - `QT_AUTO_SCREEN_SCALE_FACTOR=1`
    - `QT_SCALE_FACTOR=1.0`
    - `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1.0`
   None of these attempts resolved the issue.

Any help is greatly appreciated.

**Comment by akissinger** [comment]
Hi Bruno! I haven't made a new release of tikzit for a long time, mainly because the windows/macOS builds keep breaking. I will try to do this soon(ish?). In the meantime, if you build tikzit from source you shouldn't have this problem.
