### ISSUE TITLE
Isolated Export then Import

### ISSUE THREAD

**Issue by cuppajoeman** [tikzit/tikzit#147]
I am using tikzit to create tikz code which I can then run through https://tikzjax.com/ to allow for a simple workflow of creating tikz to authoring online.

To load tikzit code in LaTeX various files are required before anything renders, as documented on the site we have:
```tex
% paper.tex

\documentclass{article}
\usepackage{tikzit}
\input{sample.tikzstyles}

\begin{document}

A tikz picture as an equation:
\begin{equation}
  \tikzfig{fig1}
\end{equation}

A centered tikz picture:
\ctikzfig{fig1}

\end{document}
```
to be required, which requires a package, an input file as well as the figure file. On the side of tikzjax, we currently don't have support for external packages, so just using vanilla tikz and no external files allowed as of today.

Therefore if I generate minimal tikz project being a figure with a single line:

```tex
\begin{tikzpicture}
	\begin{pgfonlayer}{nodelayer}
		\node [style=none] (0) at (-2, 0) {};
		\node [style=none] (1) at (2, 0) {};
	\end{pgfonlayer}
	\begin{pgfonlayer}{edgelayer}
		\draw (0.center) to (1.center);
	\end{pgfonlayer}
\end{tikzpicture}
```

tikzjax would not be able to support this as it doesn't know what `style=none` is nor `nodelayer` and `edgelayer`

Getting it to work would require the following modifications (removal of pgfonlayer envs and custom styles defined)

```tex
\begin{tikzpicture}
        \node (0) at (-2, 0) {};
        \node (1) at (2, 0) {};
        \draw (0.center) to (1.center);
\end{tikzpicture}
```

Therefore I was curious if a new export and import feature could be added which has the ability to put all the info required to render the tikz diagram into one single `tikzpicture` environment so that we don't have to rely on external packages nor external files.

**Comment by lichengzhang1** [comment]
Hello, maybe you can see [tikzit.sty](https://github.com/tikzit/tikzit/blob/master/tex/sample/tikzit.sty).
For example, 
```
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{backgrounds}
\usetikzlibrary{arrows}
\usetikzlibrary{shapes,shapes.geometric,shapes.misc}

\pgfdeclarelayer{edgelayer}
\pgfdeclarelayer{nodelayer}
\pgfsetlayers{background,edgelayer,nodelayer,main}
\tikzstyle{none}=[inner sep=0mm]
\tikzstyle{new style 0}=[circle,draw]
%\tikzset{new style 0/.style={circle,draw}}

\begin{document}
\begin{tikzpicture}
    \begin{pgfonlayer}{nodelayer}
        \node [style=new style 0] (0) at (-10, 2) {};
        \node [style=new style 0] (1) at (-10, 0) {};
        \node[style=none](2) at (-10,1){$g$};
    \end{pgfonlayer}
    \begin{pgfonlayer}{edgelayer}
        \draw [bend left=90, looseness=2.75] (0) to (1);
        \draw [bend right=90, looseness=2.75] (0) to (1);
    \end{pgfonlayer}
\end{tikzpicture}
\end{document} 
```
![image](https://github.com/tikzit/tikzit/assets/82444903/c64a0882-96b6-4085-ac35-99138fe85270)

**Comment by akissinger** [comment]
This is quite a specific use case. It seems like a better solution would be to extend tikzjax to allow a small preamble to be executed before each tikz figure. (or just paste it in by hand)

Basically, you need the dozen or so PGF/tikz calls from [tikzit.sty](https://github.com/tikzit/template-quantum/blob/master/tikzit.sty) and the contents of your `tikzstyles` file (if you've defined some styles).
