### ISSUE TITLE
Oval shape error

### ISSUE THREAD

**Issue by cauachagas** [tikzit/tikzit#15]
I discovered Tikzit recently. It's a great tool.

I just found a error. The oval style generates a compile error. As a suggestion, this style can be replaced by ellipse. Other styles, such as "regular polygon", "cross out" and "star", are missing for the tool to be perfect. However, for those who are familiar with the Tikz package, setting the preamble to use other styles is easy.

Anyway, great tool!

**Comment by akissinger** [comment]
I'm glad you like it. Currently, I'm gearing up for a release of tikzit 2.0, which is a pretty substantial rewrite, so I'm going to close this issue for now. Feel free to open a new one if tikzit 2 has similar troubles with shapes.
