### ISSUE TITLE
Debian and Ubuntu packages

### ISSUE THREAD

**Issue by gspr** [tikzit/tikzit#16]
The [Linux download page](https://tikzit.github.io/linux/) on the TikZiT website currently refers Debian users to an OpenSUSE package, and Ubuntu users to my PPA. I am currently maintaining a TikZiT package for [Debian](https://tracker.debian.org/pkg/tikzit), which has also migrated to [Ubuntu](https://launchpad.net/ubuntu/+source/tikzit). It'll be a part of Debian's Buster release, and is also present in the latest Ubuntu release.

I suggest that the web pages just advice Debian and Ubuntu users to get these package from the official repositories.

**Comment by akissinger** [comment]
I've now made an official release of TikZiT (2.0 RC2). The new install instructions for linux are distro-independent (using a pre-compiled binary w/ bundled Qt libs), see: https://tikzit.github.io/

Once the new version makes it into Debian/Ubuntu repos, I'll add a paragraph suggesting those users (apt-)get it from there.

**Comment by gspr** [comment]
OK. I've adapted my Debian package for 2.0-RC2. When the final 2.0 is out, I'll update my package to that and upload.

I was actually considering whether to wait longer; do you think some users will miss the PDF preview feature of 1.0?

**Comment by akissinger** [comment]
Possibly, but given 2.0 has much better stability and usability, I think most will prefer 2.0 on balance.

**Comment by akissinger** [comment]
sounds good. closing for now (n.b. I've added PDF preview as a feature req for 2.1)
