### ISSUE TITLE
Matrix doesn't work

### ISSUE THREAD

**Issue by Spenhouet** [tikzit/tikzit#17]
I tried to add a matrix but it just give me a parser error.

Example code:

```
\begin{tikzpicture}
    \matrix (mtr) [matrix of nodes, nodes={draw}]
    {
        0 & 0 & 0 & 1\\
        0 & 0 & 0 & 1\\
        0 & 0 & 0 & 1\\
    };
\end{tikzpicture}
```

**Comment by akissinger** [comment]
TikZiT only parses a subset of TikZ, which does not include matrices. Details are in this (somewhat outdated) manual: http://tikzit.github.io/manual.html , which will be updated soon.
