### ISSUE TITLE
PDF preview

### ISSUE THREAD

**Issue by akissinger** [tikzit/tikzit#21]
TikZiT 1 had a PDF preview feature. This is planned for (re-)introduction TikZiT 2.1.

In the mean time, a decent work-around (for papers that take a long time to compile) is to create a file called e.g. `scratch.tex`, which just includes some minimal header tex and a single `\tikzfig` command and build this in your LaTeX editor to do previews.

**Comment by akissinger** [comment]
done!

**Comment by adigitoleo** [comment]
I'm not seeing any previews on tikzit 2.1.6 (Linux). Probably my fairly nonstandard setup is to blame. My Qt runs on Wayland (I have `qt5-wayland`) and normally for pdf previews I just use zathura with the mupdf backend.

Export works, and the pdf seems to build fine inside /tmp, but then it is being deleted? I can't see the file there.

Some ideas, don't know how eassy they are to implement:
- option for png preview
- put a preview button in the main toolbar
- put an "export as" button in the File manu so we don't have to go through preview necessarily
