### ISSUE TITLE
TikZiT on dark Qt theme

### ISSUE THREAD

**Issue by zamdzhiev** [tikzit/tikzit#22]
The TikZiT appearance is pretty heavy on the eyes when used with the Breeze Dark Qt theme of KDE.

[This is how the portable binary looks like on Debian Stable with the above theme.](https://i.imgur.com/XMuV97R.png)

I think it is best that TikZiT is used on a white background. Perhaps the easiest solution is to simply ignore the Qt theme set by the operating system. According to the documentation, this can be achieved by simply adding one line of code in main() :

QApplication::setDesktopSettingsAware(false);

right before you initialize the main application. See [here](http://doc.qt.io/qt-5/qguiapplication.html#setDesktopSettingsAware) for the official documentation.

I tested this within a flatpak build and it seems fine. But then again, the flatpak build ignores the desktop theme anyway on my machine.

I am not submitting it as a pull request, because I have no idea whether this breaks the appearance on any other systems (I can't really test this).

P.S. Congrats on the soon-to-be-released TikZitT 2.0, looks pretty good!

**Comment by akissinger** [comment]
wow, that's pretty rough.

I think it should be fixed in c858c5281, can you check it?

**Comment by zamdzhiev** [comment]
I tested a flatpak build and it seems fine.

On Debian Stable the Qt libraries are too old and I cannot build tikzit. I don't have time to setup a proper Qt dev environment right now (with the newest libraries), so I can't test the portable binary :(

**Comment by zamdzhiev** [comment]
However, I can run the portable binary which you built, so whenever you release the next RC, then I will test it for sure.

**Comment by akissinger** [comment]
ah, right. I'll close for now, but feel free to re-open if it still looks weird in RC3.
