### ISSUE TITLE
Problems with installing on Mac OSX 10.13.6

### ISSUE THREAD

**Issue by scpsg** [tikzit/tikzit#24]
I have the latest version of 10.13.6 (but not Mojave).  I downloaded the file from Github.  Put it in applications.  Changed permissions so it should run.  But when I try to open it, it says "tikzit cannot be opened because of a problem. Check with the developer to make sure tikzit works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS."   Sorry, I'm not very expert at installing such things, but need help.  Thanks.

**Comment by akissinger** [comment]
I expect this is because the macOS package was built on 10.12 Sierra. I will try updating and re-publishing a release within a few days.

**Comment by scpsg** [comment]
Thanks Aleks.   Phil Scott
