### ISSUE TITLE
NixOS package

### ISSUE THREAD

**Issue by iblech** [tikzit/tikzit#26]
Just so we don't duplicate work, let me remark that I'm preparing a NixOS package for TikZiT. Should be done soon.

**Comment by iblech** [comment]
For anyone who's interested, the NixOS package is ready and under review at https://github.com/NixOS/nixpkgs/pull/48479. (I suggest there to defer merging until 2.0 is released.)

**Comment by akissinger** [comment]
Great, thanks for letting us know.
