### ISSUE TITLE
SVG output

### ISSUE THREAD

**Issue by EdwardMorehouse** [tikzit/tikzit#37]
It would be great if TikZiT could produce SVG output for web and other non-PDF uses.

**Comment by akissinger** [comment]
This is a nice idea. A challenge is that latex is generating the final product, not tikzit. So, a potential way this could work is to call out to pdflatex then something like imagemagick to turn PDF into SVG, PNG, etc. Of course, this will only work if the user has the right tools installed.

Once I get PDF preview working, its not such a big step to do image export. So, I'll put this on the roadmap for, say, v2.2 or so.

**Comment by akissinger** [comment]
After some experiments, it looks like Qt/poppler support for translating pdf (coming from latex) to svg is a bit patchy. For now, probably the best solution is to export to PNG (if a bitmap is good enough) or export to PDF and use something like Inkscape to convert to SVG. This will be possible in the 2.1 release (see issue #49).
