### ISSUE TITLE
Frequent segfaults on Style Editor Save and Close

### ISSUE THREAD

**Issue by asetzer** [tikzit/tikzit#43]
I am getting this quite often when clicking "Save and Close" in the style editor:
> ./tikzit/bin/tikzit: line 4:  5127 Segmentation fault      LD_LIBRARY_PATH=$DIR/lib:$LD_LIBRARY_PATH QT_PLUGIN_PATH=$DIR/plugins $DIR/opt/tikzit $@

> ./tikzit/bin/tikzit: line 4:  6790 Segmentation fault      LD_LIBRARY_PATH=$DIR/lib:$LD_LIBRARY_PATH QT_PLUGIN_PATH=$DIR/plugins $DIR/opt/tikzit $@

Using tikzit 2.0. I could build a debug executable if you need more information.

EDIT: Oh and the changes *are* saved, so the crash must happen after that.

And let me take this opportunity to say thank you for this great tool!

**Comment by akissinger** [comment]
Thanks for the report. Could you attach your tikzstyles file?

**Comment by asetzer** [comment]
Sure. Current version is:

```
% TiKZ style file generated by TikZiT. You may edit this file manually,
% but some things (e.g. comments) may be overwritten. To be readable in
% TikZiT, the only non-comment lines must be of the form:
% \tikzstyle{NAME}=[PROPERTY LIST]

% Node styles
\tikzstyle{ssource}=[fill=white, draw=black, shape=rectangle, minimum height=16pt]
\tikzstyle{ssink}=[fill={rgb,255: red,191; green,191; blue,191}, draw=black, shape=rectangle, minimum height=16pt]
\tikzstyle{sliteral}=[fill=white, draw=black, shape=regular polygon, regular polygon sides=3, inner sep=-0.9pt]
\tikzstyle{sclause}=[fill={rgb,255: red,191; green,191; blue,191}, draw=black, shape=circle]
\tikzstyle{sroot}=[fill=white, draw=black, shape=regular polygon, tikzit fill={rgb,255: red,191; green,0; blue,64}, regular polygon sides=7]
\tikzstyle{sgadgetframe}=[fill=none, draw=black, shape=rectangle, minimum width=3cm, minimum height=2.8cm]

% Edge styles
\tikzstyle{normaledge}=[-]
```

Crashes every ~4-5 times I make a change.

**Comment by akissinger** [comment]
Can't reproduce yet. Have you found particular changes that do or don't trigger the crash?

In the mean time, you may be able to get a (somewhat) meaningful stack trace by modifying the shell script ~/tikzit/bin/tikzit to invoke the binary using the "catchsegv" tool:

```
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && cd .. && pwd )"
LD_LIBRARY_PATH=$DIR/lib:$LD_LIBRARY_PATH QT_PLUGIN_PATH=$DIR/plugins catchsegv $DIR/opt/tikzit $@
```

**Comment by akissinger** [comment]
I think this was (possibly) caused by a race condition around deleting and re-creating the TikzStyles object This was fixed (I think) in 644eca3d . Are you able to build from source and see if the problem goes away?

**Comment by asetzer** [comment]
I just noticed that I can't reproduce it on an empty project. After loading the tikzit file I was working on, I could reproduce it immediately. Here's my stacktrace: [tikzit_stacktrace.txt](https://github.com/tikzit/tikzit/files/2607142/tikzit_stacktrace.txt)

I will try to build from source and see if the error persists.

**Comment by akissinger** [comment]
Could you attach the tikz file?

**Comment by asetzer** [comment]
[reduction-graph-example.tikz.txt](https://github.com/tikzit/tikzit/files/2607180/reduction-graph-example.tikz.txt) (had to append .txt for github)

**Comment by akissinger** [comment]
Okay, I can now reproduce in TikZiT 2.0, but not in 644eca3. If you get the same, I will close the issue.

**Comment by asetzer** [comment]
Yes, me neither. Thank you!
