### ISSUE TITLE
scale=0.5 in tikzit.sty also scales other tikzpicture

### ISSUE THREAD

**Issue by vrublack** [tikzit/tikzit#46]
I used some tikzpicture in my tex file but then when using tikzit they were scaled down due to the scale=0.5 in tikzit.sty. I feel like this is confusing, could this be done differently?

**Comment by vrublack** [comment]
I see. How about tikzit.sty doesn't redefine \tikzfig but defines a differently named command that does the scaling? Would be less confusing than having to pass in an additional option to \tikzfig I guess.

**Comment by akissinger** [comment]
This is fixed now (see commit b703296). I came up with the following solution, which hopefully suits most people without breaking backwards-compatibility. TikZ pictures will only be scaled and have their baseline adjusted if they are: (1) included via `\tikzfig` or `\ctikzfig`, or (2) passed the `[tikzfig]` option in their `{tikzpicture}` environment.

`\tikzfig` is a non-standard command, and intended specifically for use with TikZiT. So, the default behaviour is to scale these files so they look similar to how they look in the TikZiT GUI. If you wish to avoid the scale, figures can be included e.g. with `\input`.
