### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by jluttine** [tikzit/tikzit#5]
Hi, this seems like a really nice project, I'd like to try it out. I couldn't find any instructions on how to install from source (on Arch Linux). Are there any such instructions or could you provide some basic hints on how to compile the project?

**Comment by akissinger** [comment]
Clone the source repo, then follow the instructions in
tikzit/tikzit/INSTALL .

**Comment by jluttine** [comment]
Oohps, how I missed that.. Thanks! :)
