### ISSUE TITLE
Scrolling with mouse gestures 

### ISSUE THREAD

**Issue by rossduncan** [tikzit/tikzit#53]
The main view pane doesn't scroll with mousewheel or trackpad gestures.  This would be a nice feature.  (On Mac OS X 10.14.1)

**Comment by akissinger** [comment]
Hold the shift key to 2-finger and/or wheel scroll. I did this because my touchpad is very sensitive, so I was getting unintentional scrolls and zooms all the time. This doesn't seem to be a problem for mac, so I will probably make this a setting you can turn off or on at some point.

**Comment by rossduncan** [comment]
Thanks Aleks!
