### ISSUE TITLE
[Feature] Keyboard shortcut for switching to empty style/previous style

### ISSUE THREAD

**Issue by jvdwetering** [tikzit/tikzit#59]
It would be nice to have a keyboard shortcut that switches the selected style to empty, and one that switches back to the previous style. Like in Photoshop you can use D to go back to default colours, and X to switch between the two colour swatches.

**Comment by akissinger** [comment]
Implemented in dcb4470b8cd34cd6f12d59988c1b0af9008b3420.

New keyboard shortcuts can be found under Tools > Set Style in main menu.

**Comment by akissinger** [comment]
n.b. hitting CTRL+Space clears style, hitting it again goes to the last style selected before you cleared.
