### ISSUE TITLE
Turn off text associated with nodes to manipulate figure

### ISSUE THREAD

**Issue by flyn-org** [tikzit/tikzit#62]
It might be useful to support toggling the visibility of the text/contents within the nodes displayed in the TikZiT GUI. I sometimes find that long strings of text make it difficult to manipulate a figure. This occurs in the cases where I have several lines of text in nodes which make use of the "text width" property to wrap lines.

**Comment by akissinger** [comment]
This is a good idea, thanks. Finally got around to doing it. :)

**Comment by flyn-org** [comment]
Works great. Thank you!
