### ISSUE TITLE
Why are anchors overwritten?

### ISSUE THREAD

**Issue by sg495** [tikzit/tikzit#63]
I have noticed that the anchors for edge endpoints are always overwritten, to `"center"` if the node associated to the endpoint is blank and to `""` otherwise. As far as I can tell, this happens in `edge.cpp`, inside the `Edge::updateData()` method, at the end:
```cpp
if (_source->isBlankNode()) _sourceAnchor = "center";
else _sourceAnchor = "";
if (_target->isBlankNode()) _targetAnchor = "center";
else _targetAnchor = "";
```
I understand overwriting the anchor to `"center"` for the blank nodes (which are a default of TikZiT), but I don't see why the anchors to other nodes have to be overwritten. Was there some specific reason for this behaviour?

PS: I know that rendering the anchors correctly is a pain, because TikZ makes calculations so that the endpoint ends onto the perimeter of the shape at the correct angle from the center. One practical temporary solution might be to preserve them as they appear in the files when they are loaded and ignore them in the GUI editor.

**Comment by akissinger** [comment]
If you add something as a blank node, then set its style, the anchor will remain "center" unless it is blanked out. The old behaviour in TikZiT 1 (I believe) was to preserve the anchor name unless it is "" or "center" in which case it would try to Do The Right Thing.

**Comment by sg495** [comment]
If you load a .tikz file which has anchors already in it as `int` numbers, e.g. `\draw (2.center) to (5.45);`, then the anchors are blanked out upon loading. If the anchors are `float` numbers, e.g. `\draw (2.center) to (5.236.31);`, then the program fails to load the .tikz file altogether.
