### ISSUE TITLE
Support parallel compilation

### ISSUE THREAD

**Issue by iblech** [tikzit/tikzit#66]
Sometimes parallel compilation fails, as [detailled in this log](https://hydra.nixos.org/build/93736421/nixlog/1).

It's not a big deal, I just want to mention this issue for the record.

**Comment by akissinger** [comment]
It looks like the Makefile generated by qmake doesn't realise the source generated by flex needs the header generated by bison. I must admit I'm not a QMake expert, and the flex.pri and bison.pri files are a bit of a mystery to me, so I'm not sure how to fix that.

**Comment by akissinger** [comment]
Closing for now, feel free to make a new issue if this is causing some serious problems.
