### ISSUE TITLE
Preview Grid not showing.. just blank

### ISSUE THREAD

**Issue by MichaelKhayyat** [tikzit/tikzit#67]
The grid does not show.. 
It only shows temporarily if I select part of the region. It is like there is a blanket?

**Comment by adi64** [comment]
Not the maintainer here, but - did you maybe zoom in too far?
Or are your grid colors invisible, for example white? (Check under tools -> preferences)
Also, maybe it will help if you provide a screenshot :)

**Comment by akissinger** [comment]
Depending on your monitor, the gridlines might not appear if the contrast is too low. If changing the grid colour doesn't fix the issue, please re-open.
