### ISSUE TITLE
Edge selection doesn't work on El Capitan

### ISSUE THREAD

**Issue by PiotrJander** [tikzit/tikzit#7]
Node selection is fine. But the program doesn't select edges. I am sure I am in selection mode.

Version 0.8.382

For example this edge:

``` latex
\begin{tikzpicture}
    \begin{pgfonlayer}{nodelayer}
        \node [style=none] (0) at (-2, 0.75) {};
        \node [style=none] (1) at (2.25, 0) {};
    \end{pgfonlayer}
    \begin{pgfonlayer}{edgelayer}
        \draw (0.center) to (1.center);
    \end{pgfonlayer}
\end{tikzpicture}
```

**Comment by muupan** [comment]
I have the same problem on El Capitan 10.11.5. I cannot select edges.

**Comment by Kappie** [comment]
Same problem here.

**Comment by akissinger** [comment]
This is a known bug. It should be fixed if you download the latest version from Sourceforge.

https://sourceforge.net/projects/tikzit/

**Comment by Kappie** [comment]
Thanks! It works absolutely great. I'm very grateful. Sorry for typing in caps lock, by the way.
