### ISSUE TITLE
Lost style palette on Mac

### ISSUE THREAD

**Issue by emmanuelito** [tikzit/tikzit#70]
On MacOS. I stupidly closed the style palette. 
Can't get it back !
I tried:
- remove ~/Library/Saved Application State/io.github.tikzit.savedState
- remove ~/Library//Preferences/com.tikzit.tikzit.plist
- reinstalling the app
without success (didn't reboot yet, however).

**Comment by adi64** [comment]
Unfortunately I don't have a Mac - on Linux, I can right-click the toolbar (or menu bar) and open it again by clicking on the "Styles" checkbox, like so:

![image](https://user-images.githubusercontent.com/5867277/70240936-6cf41b80-176e-11ea-9e70-481df48f0e81.png)

Is this possible on Mac?

**Comment by emmanuelito** [comment]
Yes, it works !
Thank you so much.
This trick is not intuitive although.
