### ISSUE TITLE
Missing dll jpeg62.dll

### ISSUE THREAD

**Issue by liltaylor** [tikzit/tikzit#73]
In the Windows version, on startup, a pop up appears that essentially says the jpeg62.dll is missing from the system. The app does not start.

**Comment by akissinger** [comment]
Sorry, I haven't been watching the issue track for a couple of months. What version of windows are you using?

**Comment by liltaylor** [comment]
Edition: Windows 10 Enterprise
Version: 1709
OS Build: 16299.1451

**Comment by akissinger** [comment]
Hmm, curious. Are you using the windows release (ZIP file)? If so, do you see jpeg62.dll in the same directory as tikzit.exe?

**Comment by liltaylor** [comment]
That was the first thing I checked, and, no, it wasn't there,
but I have downloaded again the .zip and, alas, there it is!
LOL! 

maybe I have deleted it inadvertently? 
it works like a charm now,
sorry for the time I have let you waste on this..
and thank you

**Comment by akissinger** [comment]
No problem. I prefer a false alarm to debugging some windows DLhell :)
