### ISSUE TITLE
How to include mathbb symbols

### ISSUE THREAD

**Issue by tylermanning** [tikzit/tikzit#78]
I can add regular math symbols and even \mathcal symbols but using \mathbb breaks previewer. How can I fix this?

**Comment by akissinger** [comment]
The default preamble tikzit uses for previews is very minimal, and doesn't include any of the ams packages. You can fix this by creating a .tikzdefs file (see https://tikzit.github.io/#custom) and adding a line:

    \usepackage{amsmath,amsfonts,amssymb}

**Comment by tylermanning** [comment]
Beautiful thanks!
