### ISSUE TITLE
edge parser failing to handle more cases where more than one node is present

### ISSUE THREAD

**Issue by 0xACE** [tikzit/tikzit#79]
`parse error:  syntax error, unexpected node, expecting to  line: 7`

```
\begin{tikzpicture}
	\begin{pgfonlayer}{nodelayer}
		\node [style=none] (0) at (-1.75, 0) {};
		\node [style=none] (1) at (1.5, 0) {};
	\end{pgfonlayer}
	\begin{pgfonlayer}{edgelayer}
		\draw (0.center) node [auto] {a} to node [auto] {b} (1.center) node [auto] {c};
	\end{pgfonlayer}
\end{tikzpicture}
```

which is a valid tikz figure:

![image](https://user-images.githubusercontent.com/1482942/80279316-5aae5600-86ec-11ea-9e44-897fb88d270e.png)

my early guess is that `tikzparser.y` needs to account for this, and that `edge->edgeNode()` has to become a list of `NodeItem` or introducing `head`, `mid`, `tail` -`edgeNodes`.

What is your opinion on this? As I'm not sure how feature complete you expect this program to be...

**Comment by akissinger** [comment]
My intention has always been to parse a small subset of TikZ to keep things simple. Generally, if a visual effect can be accomplished already, e.g. by using some extra blank nodes or something, I tend to avoid adding any more complexity to the Graph data structure.

On a related note, the parser now handles chains of "to" commands under the same \draw statement. It creates a Path, which is a logical grouping of Edge objects which are meant to be drawn continuously and (optionally) filled.
