### ISSUE TITLE
It can not run in the macOS Sierra?

### ISSUE THREAD

**Issue by sxdxyxy** [tikzit/tikzit#8]
Does anyone has the same issue with me?

**Comment by akissinger** [comment]
The latest version (1.1) for macOS runs on Sierra. It is available from: https://sourceforge.net/projects/tikzit/?source=directory

**Comment by Joshua1989** [comment]
Seems version 1.1 still doesn't work on macOS Sierra 10.12.2

**Comment by sxdxyxy** [comment]
the same issue for me, It can not run in Sierra 10.12.3. is shown as a grey forbidden icon, and if you try to run it, pop up a message: You can't use this version of the application "TikZiT" with this version of macOS.

**Comment by akissinger** [comment]
It turns out sourceforge had the incorrect file labelled as the "1.1" release. This is fixed now, so it should work if you try the download again.

**Comment by sxdxyxy** [comment]
It really works, thank you very much.
