### ISSUE TITLE
Question: Accuracy of tikzscene

### ISSUE THREAD

**Issue by 0xACE** [tikzit/tikzit#82]
Hey, I just wanted to say that I love this app. I try to work on it in my free time.

1. My question what are your expectations of the accuracy in rendering the tikzscene?

![post](https://user-images.githubusercontent.com/1482942/82743624-77769180-9d5d-11ea-94be-218cf270413a.png)
*Image showing my rendering vs `latex` vs `master`*

I'm having trouble getting edge loops get the correct size for large items and small items at the same time... I guess somewhere the scaling is off... Maybe it's related to DPI settings? Also I guess this also breaks if users have different DPI-settings or different font sizing, but that can be fixed at a later stage, as of now "It works on my machine".

Currently I'm thinking of prioritizing smaller sizing for small nodes, and leaving edge loops incorrect for larger nodes, because I think small nodes are more common.

2. What about including `computer modern` font in the program?

![cap](https://user-images.githubusercontent.com/1482942/82743834-3af86500-9d60-11ea-83a9-cbe2a0499668.png)
*Image showing my rendering vs `latex` vs `master`*

This helps a lot with the sizing issues I've been having.

So far my working branch has:

* Implemented support for settings edge labels by double clicking
* the previous edge double click is now right click activated
* labels for edges can explicitly set placement by Ctrl+Numpad<Number> (where `zero = auto`, default) ![image](https://user-images.githubusercontent.com/1482942/82743966-20bf8680-9d62-11ea-8023-dd9e42542a32.png)
* Labels are assuming they support `\newline`'s (it can detect the `align` and `size` properties, but meh, atm I have other priorities)
* Added encoding/decoding of certain non ASCII characters as I propsed in #75 
* added `\varepsilon` to `TexConstants()` (Also added also those special encodings from the ASCII encoder)
* Support for rendering of various shapes
* Will depend on the discussion in #79 

The reason I went through all this is because it makes it easier to deal with diagrams containing text as various nodes will change sizes etc...

3. I have the intention of adding a 3rd class of styles into tikzit. They will represent "modifiers" instead of having 1 red node and 1 red arrow, you just apply this "red modifier" which changes the fill color and what not... What do you think about this?

I hope this post makes sense, it takes too long for me to organize a proper discussion regarding this, but I think it's time I check with you. Cheers

**Comment by akissinger** [comment]
Hi 0xACE, thanks for your help answering people's questions. All of these additions on your branch look really cool! I'm wondering what is the best way to go about upstreaming some of it, possibly a little bit at a time. I tend to be quite conservative about adding new features, in order to keep things relatively stable. Nothing like a nasty tikzit crash ahead of a big paper deadline. :)

Do you have a fork on github?

**Comment by 0xACE** [comment]
> Hi 0xACE, thanks for your help answering people's questions. All of these additions on your branch look really cool!

Hi, thanks :D

>I'm wondering what is the best way to go about upstreaming some of it, possibly a little bit at a time.

I don't have a fork on github but I'll make it easy for you. I'll supply patches as separate pull requests where you can pick w/e you like to keep upstream.

>I tend to be quite conservative about adding new features, in order to keep things relatively stable.

I understand.

>Nothing like a nasty tikzit crash ahead of a big paper deadline. :)

Haha, oh yeah I know exactly what you are talking about ;). I patched out some of the segfaults from `master`.

But, I have been messing around with this since I proposed these changes, and I neglected to maintain commits of these changes. Therefore I need to do **a lot** of cleanup before submitting a PR.

Judging by my schedule atm I will not be able to look at this until October.

**Comment by akissinger** [comment]
That's fine. I'll try to be a bit more responsive, but it might be tricky as it comes into term time. :) Feel free to drop me an email if you are doing some work on tikzit.
