### ISSUE TITLE
No image on tool buttons (Fedora 32)

### ISSUE THREAD

**Issue by Krantz-XRF** [tikzit/tikzit#84]
Just installed TikZiT using `dnf install tikzit` (version 2.1.5) on Fedora 32. Now the button images are missing:

![Screenshot](https://user-images.githubusercontent.com/17098235/89251065-b623a480-d648-11ea-8a72-2abe1073b1ea.png)

Set light theme in Gnome does not help:

![Screenshot Light Theme](https://user-images.githubusercontent.com/17098235/89251256-1fa3b300-d649-11ea-84ba-8d537baf3eb0.png)

**Comment by 0xACE** [comment]
When you run it form terminal, do you see any errors printed?

Looking at the source code, these icons are included within the sourcecode itself.. unless you somehow built the project excluding resources...

**Comment by akissinger** [comment]
Hmm, this looks like a problem with the Fedora RPM package. I'm not sure who maintains this. Maybe they are lurking here or @gspr knows?

**Comment by akissinger** [comment]
As a temporary workaround, you can try using the "Portable Binary" version on tikzit.github.io .

**Comment by gspr** [comment]
Aleks Kissinger <notifications@github.com> writes:

> Hmm, this looks like a problem with the Fedora RPM package. I'm not
> sure who maintains this. Maybe they are lurking here or @gspr knows?

Hmm, no, this bug is not reproducible for the current Debian package. It
works fine.

I assume the Fedora package is not in any way based on the Debian
one. Maybe you can find more info here at

 https://koji.fedoraproject.org/koji/buildinfo?buildID=1570511

**Comment by akissinger** [comment]
Thanks for the link Gard, that looks like the page I was looking for. It mentions Michael Petulo / @flyn-org as the last one to do an upstream to Fedora, so maybe they know why this is happening.

**Comment by flyn-org** [comment]
I do indeed maintain the Fedora TikZiT packages.

The TikZiT build process seems to embed TikZiT's button images in the tikzit binary. This seems to be the case with the binary from my Fedora package:
```
$ grep polygon tikzit-2.1.5/images/tikzit-tool-select.svg
<polygon class="st0" points="15.5,9.5 48.5,36.5 28.5,36.5 15.5,52.5 "/>
$ strings /usr/bin/tikzit | grep polygon
<polygon class="st0" points="15.5,9.5 48.5,36.5 28.5,36.5 15.5,52.5 "/>
```
Something else must be preventing TikZiT from rendering these button images on @Krantz-XRF's  computer. I think an answer to the question above asking for the terminal output resulting from running `tikzit` might help. I do not have this problem on my computer, and I am also running Fedora 32.

**Comment by Krantz-XRF** [comment]
Sorry for the late reply. This is what I get from the terminal:

```text
$ tikzit
QSocketNotifier: Can only be used with threads started with QThread
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
QSocketNotifier: Can only be used with threads started with QThread
```

FYI, I have `LANG=zh_CN.UTF-8`, though I don't think it is related.

**Comment by flyn-org** [comment]
For what it is worth, I just ran `LANG=zh_CN.UTF-8 tikzit`, and the button images worked fine.

When I run TikZiT, I see:
```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
```
but not
```
QSocketNotifier: Can only be used with threads started with QThread
```

What do you see when you run `sha256sum /usr/bin/tikzit`?

**Comment by Krantz-XRF** [comment]
```text
$ sha256sum /usr/bin/tikzit
8a892be9f00a3a8a6f09359bcbfc1f884d78fddb6d95f6fe2a9885cb9fedad38  /usr/bin/tikzit
$ ldd /usr/bin/tikzit
	linux-vdso.so.1 (0x00007fff5bbd2000)
	libpoppler-qt5.so.1 => /lib64/libpoppler-qt5.so.1 (0x00007f23cd290000)
	libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007f23ccbea000)
	libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007f23cc681000)
	libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007f23cc4f8000)
	libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007f23cbfdd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f23cbfbb000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f23cbdc9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f23cbc83000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f23cbc68000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f23cba9e000)
	libpoppler.so.94 => /lib64/libpoppler.so.94 (0x00007f23cb74b000)
	libQt5Xml.so.5 => /lib64/libQt5Xml.so.5 (0x00007f23cb70b000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f23cb644000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f23cb5bc000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f23cb585000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f23cb56b000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f23cb489000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f23cb482000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f23cb429000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f23cb392000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f23cb0a5000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f23cafee000)
	libicui18n.so.65 => /lib64/libicui18n.so.65 (0x00007f23cace7000)
	libicuuc.so.65 => /lib64/libicuuc.so.65 (0x00007f23caaff000)
	libpcre2-16.so.0 => /lib64/libpcre2-16.so.0 (0x00007f23caa72000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f23ca948000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f23cd3e2000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f23ca8fd000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f23ca878000)
	libopenjp2.so.7 => /lib64/libopenjp2.so.7 (0x00007f23ca824000)
	liblcms2.so.2 => /lib64/liblcms2.so.2 (0x00007f23ca7c4000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f23ca742000)
	libsmime3.so => /lib64/libsmime3.so (0x00007f23ca716000)
	libnss3.so => /lib64/libnss3.so (0x00007f23ca5db000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f23ca597000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f23ca584000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f23ca550000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f23ca407000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f23ca3f2000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f23ca339000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f23ca315000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f23ca22a000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f23ca211000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f23ca208000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f23ca1f6000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f23ca1ef000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f23ca1d5000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f23ca1ca000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f23ca1a0000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f23ca17d000)
	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f23ca05c000)
	libicudata.so.65 => /lib64/libicudata.so.65 (0x00007f23c85a9000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f23c8530000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f23c8501000)
	libjbig.so.2.1 => /lib64/libjbig.so.2.1 (0x00007f23c84f1000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007f23c84be000)
	libplc4.so => /lib64/libplc4.so (0x00007f23c84b7000)
	libplds4.so => /lib64/libplds4.so (0x00007f23c84b2000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f23c8486000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f23c8457000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f23c8433000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f23c842d000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f23c8394000)
```

**Comment by Krantz-XRF** [comment]
I just downloaded the portable Linux binary, and the icons showed up, but GNOME theme did not apply to TikZiT.

I found out `bin/tikzit` from the portable package is just a shell script, which runs `opt/tikzit`, so I tried running the two in the terminal. Below are the results:

| | `bin/tikzit` | `opt/tikzit` |
|-|-|-|
| Screenshots | ![图片](https://user-images.githubusercontent.com/17098235/90038936-96e7df80-dcf8-11ea-82e5-982a599f5e01.png) | ![2020-08-13 00-06-31 的屏幕截图](https://user-images.githubusercontent.com/17098235/90039176-e201f280-dcf8-11ea-87e4-2240c9b44f63.png) |
| Icons | :heavy_check_mark: | :x: |
| GNOME Theme | :x: | :heavy_check_mark: |
| Output | Nothing | 3 Warnings (same as above) |

I suspect this issue is rooted in the runtime libraries, for `bin/tikzit` runs `opt/tikzit` with custom libraries in the portable package. Though I haven't find out which library is causing this problem yet.

**Comment by flyn-org** [comment]
Did you install any of the relevant libraries from a source other than Fedora packages? Do you have the latest version of the Fedora-provided packages (`dnf update`)? Is there anything non-standard about your Fedora install?

**Comment by Krantz-XRF** [comment]
1. This is a fresh install of Fedora 32 and TikZiT is the first several softwares I installed. I might be using the TUNA mirror of Fedora packages (for it should be the fastest here in China, and got automatically chosen), but that mirror is included in the official mirror list.
2. I just checked for update before writing and posting the last comment, and everything is up to date now.
3. I installed some GNOME extensions, but I tried disabling all extensions in `gnome-tweak-tool`, and the issue persists. I installed Zoom RPM package from the official website, VSCode by adding the official RPM repository, and Haskell stack from the official website. (I believe these would not be relevant.) Everything else is installed via `dnf` (ffmpeg, TeX Live, etc.).

The Qt package from the portable package is Qt 5.9.5 and the "global" Qt package is 5.14.2. (I got these information from the configuration file `~/.config/tikzit/tikzit.conf`).

**Comment by 0xACE** [comment]
What output do you get from running this in your shell?
```
tikzit 2>/dev/null & pid="$!"; sleep 2 && lsof -p "$pid" | grep -i "qt\/plugins"; kill "$pid"
```

I'm expecting you to be missing these references references to

```
/usr/lib/qt/plugins/xcbglintegrations/libqxcb-glx-integration.so
/usr/lib/qt/plugins/iconengines/libqsvgicon.so
/usr/lib/qt/plugins/imageformats/libqsvg.so
/usr/lib/qt/plugins/imageformats/libqpdf.so
/usr/lib/qt/plugins/imageformats/libqjpeg.so
/usr/lib/qt/plugins/imageformats/libqico.so
/usr/lib/qt/plugins/imageformats/libqgif.so
/usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
/usr/lib/qt/plugins/platforms/libqxcb.so
```

I suspect you are missing at least one of these:

```
/usr/lib/qt/plugins/iconengines/libqsvgicon.so
/usr/lib/qt/plugins/imageformats/libqsvg.so
/usr/lib/qt/plugins/imageformats/libqpdf.so
/usr/lib/qt/plugins/imageformats/libqjpeg.so
/usr/lib/qt/plugins/imageformats/libqico.so
/usr/lib/qt/plugins/imageformats/libqgif.so
```

I'm not familiar with fedora, but in archlinux you get it from `qt5-base` https://www.archlinux.org/packages/extra/x86_64/qt5-base/

**Comment by flyn-org** [comment]
Here is what I have on my Fedora computer:
```
$ rpm -qf /usr/lib64/qt5/plugins/iconengines/libqsvgicon.so 
qt5-qtsvg-5.14.2-1.fc32.x86_64
$ rpm -qf /usr/lib64/qt5/plugins/imageformats/*
qt5-qtbase-gui-5.14.2-5.fc32.x86_64
qt5-qtbase-gui-5.14.2-5.fc32.x86_64
qt5-qtbase-gui-5.14.2-5.fc32.x86_64
qt5-qtsvg-5.14.2-1.fc32.x86_64
```
@Krantz-XRF, can you confirm that one or more of these are missing and that installing them fixes your problem? If so, then I will add them as dependencies to the package.

**Comment by Krantz-XRF** [comment]
@flyn-org Installing `qt5-qtsvg` immediately solves the problem. Thanks very much!

**Comment by flyn-org** [comment]
I just pushed a new Fedora version with a hard requirement on qt5-qtsvg. My hope is to prevent this problem from happening again. Please see https://koji.fedoraproject.org/koji/taskinfo?taskID=49198986.

Thank you, @0xACE for helping to diagnose.
