### ISSUE TITLE
How to draw a rectangle?

### ISSUE THREAD

**Issue by jagjordi** [tikzit/tikzit#85]
Is it possible to draw a rectangle, i.e.
```\draw (0,0) rectangle (1,1);```
without having to use the `\node` sytax?

**Comment by 0xACE** [comment]
Yes, infact `tikzit` is actually generating `tikz` code under it's own environment. The problem is that the `tikzit` parser doesn't accept it (You can't press `CTRL-T` after pressing `CTRL-J`)

![issue-85](https://user-images.githubusercontent.com/1482942/89401250-889c3100-d704-11ea-9515-2a2e9790a2e6.png)

My goal is to eventually support resizing of nodes. But I will only do that after I add support for loading images.

Anyhow, Adding support for `unknown` objects in the parser is possible but they'd all be rendered with a place holder just like how `source` engine did:


![issue-85-source_error](https://user-images.githubusercontent.com/1482942/89401611-0fe9a480-d705-11ea-92d9-c02f1484013b.jpg)

**Comment by jagjordi** [comment]
I quite new to tikzit, I had been using tikzedt for some time and I was used to the that editing style. So it feels diferent the way tikzit generated the code, like if you want to draw a polyline, i.e. `\draw (0,0) -- (0,1) -- (1,1);` could you do that with the tikzit gui?

**Comment by 0xACE** [comment]
Btw I sort of neglected to solve your problem. You could probably get what you want with other clever tricks...

![cap](https://user-images.githubusercontent.com/1482942/89402083-d2d1e200-d705-11ea-8173-76e55250ec1e.png)

If you had something specific in mind, maybe I could give you some ideas.

> I quite new to tikzit, I had been using tikzedt for some time and I was used to the that editing style. So it feels diferent the way tikzit generated the code

Ah, I see. dw I'm also new. I just adopted this software once my very old computer managed to run this fairly fast (Though latex is another issue).
>like if you want to draw a polyline, i.e. `\draw (0,0) -- (0,1) -- (1,1);` could you do that with the tikzit gui?

![poly](https://user-images.githubusercontent.com/1482942/89403187-77085880-d707-11ea-9db4-6071ae3a2a90.gif)

You create empty nodes and then draw edges between them.

**Comment by akissinger** [comment]
Yes, this is the recommended way of making shapes which aren't just single nodes. In the latested git version, you can join sequences of edges into a path with `CTRL+P`, which enables you to fill and makes a (slight) difference in visual appearance. I'm still ironing out some UI issues, so I haven't made a release of that yet.

**Comment by ribeirompl** [comment]
@0xACE That is quite a nice collection of tikzstyles. Would you be willing to share them?

**Comment by 0xACE** [comment]
@ribeirompl my build of `tikzit` is different. beware of differences from my setup. anyhow these are my settings I use across all my files that is compatible with `master`

`tikz.tikzstyles`
```
% TiKZ style file generated by TikZiT. You may edit this file manually,
% but some things (e.g. comments) may be overwritten. To be readable in
% TikZiT, the only non-comment lines must be of the form:
% \tikzstyle{NAME}=[PROPERTY LIST]

% Node styles
\tikzstyle{L-textX}=[align=left, tikzit shape=none]
\tikzstyle{circleX}=[draw=black, shape=circle, align=center]
\tikzstyle{dbl-circleX}=[draw=black, shape=circle, double, align=center]
\tikzstyle{dash-circleX}=[draw=black, shape=circle, dashed, align=center]
\tikzstyle{rectangleX}=[draw=black, shape=rectangle, align=left]
\tikzstyle{dash-rectangleX}=[draw=black, shape=rectangle, dashed, align=left]
\tikzstyle{gray-rectangleX}=[fill={rgb,255: red,217; green,217; blue,217}, draw=black, shape=rectangle, align=left]
\tikzstyle{nw-lines-rectangleX}=[fill=red, draw=black, shape=rectangle, align=left]
\tikzstyle{aanw-lines-rectangleX}=[draw=black, shape=rectangle, pattern=north west lines, pattern color=gray, align=left, tikzit shape=strike out]
\tikzstyle{diamondX}=[draw=black, shape=diamond, align=center]
\tikzstyle{cross-textX}=[draw=black, shape=cross out, align=center]
\tikzstyle{ellipseX}=[draw=black, shape=ellipse, align=center]
\tikzstyle{hexagonX}=[draw=black, shape=regular polygon, regular polygon sides=6, align=center, minimum size=0.58cm]
\tikzstyle{triangleX}=[draw=black, shape=regular polygon, regular polygon sides=3, align=center]
\tikzstyle{cylinderX}=[draw=black, shape=cylinder, shape border rotate=90, align=center, aspect=0.25]
\tikzstyle{round-rectangleX}=[draw=black, shape=rectangle, rounded corners, align=left]
\tikzstyle{cloudX}=[draw=black, shape=cloud, align=center]
\tikzstyle{strike-textX}=[draw=black, shape=strike out, align=center]
\tikzstyle{bangX}=[draw=black, shape=starburst, align=center]
\tikzstyle{signalX}=[draw=black, shape=signal, align=left]
\tikzstyle{starX}=[draw=black, shape=star, align=center]
\tikzstyle{tight-circleX}=[draw=black, shape=circle, align=center, inner sep=0.02cm]
\tikzstyle{tight-rectangleX}=[draw=black, shape=rectangle, align=left, inner sep=0.02cm]
\tikzstyle{tight-diamondX}=[draw=black, shape=diamond, align=center, inner sep=0.02cm]
\tikzstyle{tight-triangleX}=[draw=black, shape=regular polygon, regular polygon sides=3, align=center, inner sep=0.02cm]
\tikzstyle{tight-round-rectangleX}=[draw=black, shape=rectangle, rounded corners, align=left, inner sep=0.02cm]
\tikzstyle{wide-diamondX}=[draw=black, shape=diamond, align=left, aspect=2]
\tikzstyle{invis-tight-text}=[shape=ellipse, inner sep=0.02cm, align=center]
\tikzstyle{L-invis-tight-text}=[shape=ellipse, inner sep=0.02cm, align=left]
\tikzstyle{cross-lines-rectangleX}=[draw=black, shape=rectangle, pattern=crosshatch, pattern color=gray, align=left, tikzit shape=cross out]
\tikzstyle{fRedY}=[fill=red]
\tikzstyle{fGrayY}=[fill={rgb,255: red,217; green,217; blue,217}]
\tikzstyle{s1CharY}=[minimum size=0.5cm]

% Edge styles
\tikzstyle{arrowZ}=[->, align=left]
\tikzstyle{dash-edgeZ}=[-, align=left, dashed]
\tikzstyle{dash-arrowZ}=[->, align=left, dashed]
\tikzstyle{darrowZ}=[<->, align=left]
\tikzstyle{dash-darrowZ}=[<->, align=left, dashed]
\tikzstyle{reg-grayZ}=[-, align=left, fill={rgb,255: red,217; green,217; blue,217}, draw=black]
\tikzstyle{reg-nw linesZ}=[-, align=left, pattern=north west lines, pattern color=gray, draw=black]
\tikzstyle{wifiZ}=[-, snake=expanding waves, segment angle=8]
\tikzstyle{wiggleZ}=[-, snake=snake]
\tikzstyle{triangle-arrowZ}=[-, snake=triangles]
\tikzstyle{thick-arrowZ}=[->, very thick]
\tikzstyle{wiggle-arrowZ}=[snake=snake, ->]
\tikzstyle{zigzagZ}=[-, snake=zigzag]
\tikzstyle{braceZ}=[-, snake=brace]
\tikzstyle{footZ}=[-, decorate, decoration=footprints]
\tikzstyle{thick-lineZ}=[-, very thick]
\tikzstyle{thick-dashZ}=[-, very thick, dashed]
\tikzstyle{thick-darrowz}=[<->, very thick]
```

`tikz.tikzdefs`:
```
\usetikzlibrary{automata,arrows,patterns,shapes.geometric,shapes.misc,snakes,decorations.footprints}
\tikzset{>=stealth}
```

Honestly it makes sense to create your own setup as it will make more sense what the difference is between some of the shapes that seem to be identical

**Comment by ribeirompl** [comment]
@0xACE Thanks! It will be a good starting point, as I do plan to edit it to my preferences.
Much appreciated.
