### ISSUE TITLE
Missing $ inserted error

### ISSUE THREAD

**Issue by DavidJaz** [tikzit/tikzit#91]
I tried to use tikzit to add a figure to my document following the tutorial, but I get the error "Missing $ inserted" at the use of `\tikzfig` or `\ctikzfig`. 

Here is a minimal example:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{tikzit}
\input{mystyle.tikzstyles}

\begin{document}
\ctikzfig{myfigure}
\end{document}
```

**Comment by 0xACE** [comment]
Could you supply `mystyle.tikzstyles` and `myfigure.tikz` too?

Judging by the error message "Missing $ inserted" either latex is guessing you inserted a math formula or your `$` signs are not balanced.

**Comment by akissinger** [comment]
This will also happen if you have an underscore in a style name or property, which LaTeX interprets as a math subscript.

**Comment by DavidJaz** [comment]
Thanks both. Alex, I think you are right; I have removed the underscores from my style names, and it works correctly now.
