### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by ilippert** [tikzit/tikzit#95]
Running tikzit from the shell under fedora 32 gets me this error `qt.qpa.wayland: Wayland does not support QWindow::requestActivate`. 
But the software works well so far ;)

**Comment by 0xACE** [comment]
Doesn't wayland maintain some proxy software to handle these situations?

I haven't transitioned to wayland yet and cannot experiment with this yet.

I cba to read the Qt documentations but they mention a runtime command line argument: `-platform wayland` e.g. `tikzit -platform wayland`. You could try that, but I haven't even researched this.

**Comment by gspr** [comment]
> Running tikzit from the shell under fedora 32 gets me this error `qt.qpa.wayland: Wayland does not support QWindow::requestActivate`.
> But the software works well so far ;)

I'm unable to reproduce this under Wayland (SwayWM 1.5) on Debian. TikZiT works flawlessly for me, both with and without high-DPI.

**Comment by ilippert** [comment]
version 2.1.6
works for me now.
Am by now on Fedora 33.
